services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    networks: [inception]

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - www-volume:/var/www/html
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USERNAME: ${WP_USERNAME}
      WP_EMAIL: ${WP_EMAIL}
      WP_DISPLYNAME: ${WP_DISPLYNAME}
    secrets:
      - db_password
      - wp_credentials
    depends_on: [mariadb]
    networks: [inception]

  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - www-volume:/var/www/html:ro
      - ssl-volume:/etc/nginx/ssl
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on: [wordpress]
    networks: [inception]

volumes:
  www-volume:
    name: www-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/www

  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mariadb

  ssl-volume:
    name: ssl-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/ssl

networks:
  inception:
    name: inception

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_credentials:
    file: ../secrets/wp_credentials.txt

